[BUGFIX] SassError: compound selectors may no longer be extended. #1023 (#1029)
SassError: compound selectors may no longer be extended. Consider @extend .form-control, .is-invalid instead. See: https://sass-lang.com/documentation/breaking-changes/extend-compound for details.